### ISSUE TITLE
Zmienić dokumentację

### ISSUE THREAD

**Issue by KostkaBrukowa** [rafallewanczyk/TIN#13]
Należy zmienić dokumentację:
- zmienić flow pobierania danych o urzadzeniach. Teraz jest, że regulator wysyła aktualny stan, a ma być tak, że serwer prosi o dane.

**Comment by KostkaBrukowa** [comment]
- zmienić `Zmień konfigurację urządzenia` na `Zmień konfigurację urządzeń`

**Comment by rafallewanczyk** [comment]
nice!
